Repository FS-FAST-TRACK/QuizMaster, pull requests merged in 2023-11, with the labels that each got.

#54 feat: Added Quiz API endpoints.
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/20231024084534_InitialMigrationForQuizService.Designer.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/20231024084534_InitialMigrationForQuizService.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/20231106103746_QuizMasterQuestionDbInitialMigration.Designer.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/20231106103746_QuizMasterQuestionDbInitialMigration.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/QuestionDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/DetailDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/Option.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/QuestionCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/QuestionDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/Questions/IQuestion.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/Questions/MultipleChoiceQuestion.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/Questions/PuzzleQuestion.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/Questions/SliderQuestion.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/Questions/TrueOrFalseQuestion.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/Questions/TypeAnswerQuestion.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/DetailProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/QuestionProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/SeedData/QuestionTypes.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Factories/QuestionFactory.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/QuizRepository.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/IAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/MultipleChoiceAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/PuzzleAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/SliderAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/TypeAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/MultipleChoiceQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/SliderQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/TypeAnswerQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Options/Option.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Question.cs
  WebApp/backend/QuizMaster.Library.Common/QuizMaster.Library.Common.csproj
Labels: feature

#56 Feat: Roles [User/Admin] Authorization Filter and RabbitMQ Message Bus Enhancement
  WebApp/backend/QuizMaster.API.Account/Service/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Authentication/Controllers/AuthenticationController.cs
  WebApp/backend/QuizMaster.API.Authentication/Models/AuthRequest.cs
  WebApp/backend/QuizMaster.API.Authentication/Models/AuthStore.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/AuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/IAuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/RabbitMqRepository.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/QuizMasterAdminAuthorizationAttribute.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/QuizMasterAdminAuthorizationFilter.cs
  WebApp/backend/QuizMaster.Library.Common/Models/RabbitMQ_AccountPayload.cs
  WebApp/backend/QuizMaster.Library.Common/Models/Services/AuthRequest.cs
Labels: feature

#59 feat: Added Multiple choice plus audio POST API endpoints and pagination for questions.
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/QuestionDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/DetailProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/QuestionProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/ResourceParameters/CategoryResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/ResourceParameters/IResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/ResourceParameters/QuestionResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/IQuizRepository.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/QuizRepository.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/MultipleChoicePlusAudioQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Helpers/Quiz/PagedList.cs
Labels: feature

#58 Feat: JWT Authorization Bearer Implementation
  WebApp/backend/QuizMaster.API.Authentication/Controllers/AuthenticationController.cs
  WebApp/backend/QuizMaster.API.Authentication/Models/AuthenticationRequestDTO.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/RabbitMqRepository.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AuthenticationGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/QuizMasterAdminAuthorizationFilter.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/QuizMasterAuthorizationFilter.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
Labels: feature

#62 feat: Added guard for empty question details, added emptyQuestionDetail class, and remove question type guard for POST API endpoints.
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/EmptyQuestionDetail.cs
Labels: feature

#63 Feat: Added gateway for question difficulty
  WebApp/backend/QuizMaster.API.Gatewway/AutoMapper.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionDifficultyGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.Quiz/Profiles/DifficultyProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Program.cs
  WebApp/backend/QuizMaster.API.Quiz/Protos/quiz.proto
  WebApp/backend/QuizMaster.API.Quiz/Protos/quiz_difficulty.proto
  WebApp/backend/QuizMaster.API.Quiz/QuizMaster.API.Quiz.csproj
  WebApp/backend/QuizMaster.API.Quiz/Services/GRPC/DifficultyService.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/GRPC/QuestionService.cs
  WebApp/backend/QuizMaster.Library.Common/Helpers/Quiz/PagedList.cs
  WebApp/backend/QuizMasterBackend.sln
Labels: feature

#65 feat: Added General POST API endpoint. Remove individual API endpoints.
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/QuestionCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/DetailProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/QuestionProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/SeedData/QuestionTypes.cs
  WebApp/backend/QuizMaster.Library.Common/Helpers/Quiz/QuestionRepository.cs
Labels: feature

#66 Feat: API gateway for Question Service
  WebApp/backend/QuizMaster.API.Gatewway/AutoMapper.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.API.Quiz/Protos/quiz.proto
  WebApp/backend/QuizMaster.API.Quiz/Services/GRPC/QuestionService.cs
Labels: feature

#67 Feature/quizmaster api quizsession
  WebApp/backend/QuizMaster.API.QuizSession/Controllers/RoomController.cs
  WebApp/backend/QuizMaster.API.QuizSession/Controllers/SessionController.cs
  WebApp/backend/QuizMaster.API.QuizSession/Controllers/WeatherForecastController.cs
  WebApp/backend/QuizMaster.API.QuizSession/Handlers/SessionHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/Hubs/SignalR_QuizSessionHub.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/Chat.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/ChatPost.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/JoinData.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/Notification.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/SessionDTO.cs
  WebApp/backend/QuizMaster.API.QuizSession/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Repositories/IChatRepository.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Repositories/SingletonChatRepository.cs
  WebApp/backend/QuizMaster.API.QuizSession/WeatherForecast.cs
Labels: feature

#68 SignalR Hubs and Quiz Session implementation
  WebApp/backend/QuizMaster.API.QuizSession/Controllers/RoomController.cs
  WebApp/backend/QuizMaster.API.QuizSession/Controllers/SessionController.cs
  WebApp/backend/QuizMaster.API.QuizSession/Controllers/WeatherForecastController.cs
  WebApp/backend/QuizMaster.API.QuizSession/Handlers/SessionHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/Hubs/SignalR_QuizSessionHub.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/Chat.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/ChatPost.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/JoinData.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/Notification.cs
  WebApp/backend/QuizMaster.API.QuizSession/Models/SessionDTO.cs
  WebApp/backend/QuizMaster.API.QuizSession/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Repositories/IChatRepository.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Repositories/SingletonChatRepository.cs
  WebApp/backend/QuizMaster.API.QuizSession/WeatherForecast.cs
Labels: feature

#70 feat: Added QuizSessionRepository
  WebApp/backend/QuizMaster.API.QuizSession/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Repositories/QuizSessionRepository.cs
Labels: feature

#72 feat: Add question patch
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/QuestionCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/QuestionProfile.cs
Labels: feature

#75 Fix: Fixed bugs on Question API gateway service
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionGatewayController.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/QuestionProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/GRPC/QuestionService.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Question.cs
Labels: fix

#82 Feature/quizmaster api quizsession
  WebApp/backend/QuizMaster.API.Account/Controllers/AccountController.cs
  WebApp/backend/QuizMaster.API.Account/Service/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Authentication/Controllers/AuthenticationController.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/AuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/IAuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/GRPC/Service.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AuthenticationGatewayController.cs
  WebApp/backend/QuizMaster.Library.Common/Models/Services/AuthRequest.cs
Labels: refactor, fix

#83 Feat: Add Set Admin Route
  WebApp/backend/QuizMaster.API.Account/Proto/accounts.proto
  WebApp/backend/QuizMaster.API.Account/Service/InformationService.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
Labels: feature

#84 Feat: Add user audit trail
  WebApp/backend/QuizMaster.API.Account/Program.cs
  WebApp/backend/QuizMaster.API.Account/QuizMaster.API.Account.csproj
  WebApp/backend/QuizMaster.API.Account/Service/InformationService.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Monitoring/Controllers/UserAuditController.cs
  WebApp/backend/QuizMaster.API.Monitoring/Controllers/WeatherForecastController.cs
  WebApp/backend/QuizMaster.API.Monitoring/DataAccess/IUserAuditTrailRepository.cs
  WebApp/backend/QuizMaster.API.Monitoring/DataAccess/MonitoringDbContext.cs
  WebApp/backend/QuizMaster.API.Monitoring/DataAccess/UserAuditTrailRepository.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231115091318_initialDbAudit.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231115091318_initialDbAudit.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231120094711_AddQuizAuditTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231120094711_AddQuizAuditTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/MonitoringDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Monitoring/Program.cs
  WebApp/backend/QuizMaster.API.Monitoring/Proto/monitoring.proto
  WebApp/backend/QuizMaster.API.Monitoring/QuizMaster.API.Monitoring.csproj
  WebApp/backend/QuizMaster.API.Monitoring/Services/Audit/IUserAuditTrailService.cs
  WebApp/backend/QuizMaster.API.Monitoring/Services/Audit/UserAuditTrailService.cs
  WebApp/backend/QuizMaster.API.Monitoring/Services/MonitoringInfoService.cs
  WebApp/backend/QuizMaster.API.Monitoring/WeatherForecast.cs
  WebApp/backend/QuizMaster.API.Monitoring/appsettings.Development.json
  WebApp/backend/QuizMaster.Library.Common/Entities/Audits/QuizAuditTrail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Audits/UserAuditTrail.cs
  WebApp/backend/QuizMaster.Library.Common/Helpers/DateTimeHelper.cs
Labels: feature

#85 Fix: Incorrect Behavior in the Login Process - Potential Relationship to Trello Ticket #53
  WebApp/backend/QuizMaster.API.Authentication/Services/RabbitMqRepository.cs
Labels: fix
