Repository FS-FAST-TRACK/QuizMaster, pull requests merged in 2023-12, with the labels that each got.

#89 Feat: API Gateway for question set
  WebApp/backend/QuizMaster.API.Gatewway/Configuration/GrpcServerConfiguration.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.json
  WebApp/backend/QuizMaster.API.QuizSession/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Protos/quiz_set.proto
  WebApp/backend/QuizMaster.API.QuizSession/QuizMaster.API.QuizSession.csproj
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizSetServices.cs
  WebApp/backend/QuizMaster.Library.Common/Models/QuizSession/SetDTO.cs
Labels: feature

#92 Feat: Created A WebSocket
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.QuizSession/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Protos/room.proto
  WebApp/backend/QuizMaster.API.QuizSession/QuizMaster.API.QuizSession.csproj
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
Labels: feature

#94 Feature: Create Room, Join Room and Chat feature added in QuizSession
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.QuizSession/DbContexts/QuizSessionDbContext.cs
  WebApp/backend/QuizMaster.API.QuizSession/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizSetServices.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Rooms/QuizRoom.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Rooms/SetQuizRoom.cs
  WebApp/backend/QuizMaster.Library.Common/Models/QuizSession/CreateRoomDTO.cs
Labels: feature

#95 Feature: Update and Delete Room is now functional
  WebApp/backend/%USERPROFILE%/.aspnet/https/aspnetapp.pfx
  WebApp/backend/.dockerignore
  WebApp/backend/QuizMaster.API.Account/Dockerfile
  WebApp/backend/QuizMaster.API.Account/Program.cs
  WebApp/backend/QuizMaster.API.Account/Properties/launchSettings.json
  WebApp/backend/QuizMaster.API.Account/QuizMaster.API.Account.csproj
  WebApp/backend/QuizMaster.API.Account/Service/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Account/appsettings.Development.json
  WebApp/backend/QuizMaster.API.Account/appsettings.json
  WebApp/backend/QuizMaster.API.Account/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Authentication/Configuration/AppSettings.cs
  WebApp/backend/QuizMaster.API.Authentication/Dockerfile
  WebApp/backend/QuizMaster.API.Authentication/Program.cs
  WebApp/backend/QuizMaster.API.Authentication/Properties/launchSettings.json
  WebApp/backend/QuizMaster.API.Authentication/QuizMaster.API.Authentication.csproj
  WebApp/backend/QuizMaster.API.Authentication/appsettings.Development.json
  WebApp/backend/QuizMaster.API.Authentication/appsettings.json
  WebApp/backend/QuizMaster.API.Authentication/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Gatewway/Dockerfile
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/Properties/launchSettings.json
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.Development.json
  WebApp/backend/QuizMaster.API.Gatewway/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Media/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Protos/room.proto
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.Library.Common/Models/QuizSession/CreateRoomDTO.cs
  docker-compose.yml
Labels: feature

#99 fix: Creating new QuestionSet no longer allow duplicate 'QSetName'
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizSetServices.cs
Labels: fix

#101 Feat: Created a hub to get questions
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/Protos/room.proto
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.Library.Common/Models/QuizSession/QuestionsDTO.cs
Labels: feature

#103 Feat: Added a hub to get the players
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.Library.Common/Models/QuizSession/QuestionsDTO.cs
Labels: feature

#104 QuizSession Hub Authentication Implementation
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.Quiz.Tests/Services/QuizTestDataRepository.cs
  WebApp/backend/QuizMaster.API.QuizSession/Protos/room.proto
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Rooms/QuizParticipant.cs
Labels: feature

#108 Fix: Fix Question Patch
  WebApp/backend/QuizMaster.API.Quiz.Tests/Services/QuizTestDataRepository.cs
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionDetailController.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/IQuizRepository.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/QuizRepository.cs
Labels: fix

#109 Participants to Submit Answers
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/QuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Models/QuizSession/QuestionsDTO.cs
  WebApp/backend/QuizMaster.Library.Common/Models/QuizSession/SubmitAnswerDTO.cs
Labels: feature

#113 Refactor: Minor changes where updated, see documentation
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
Labels: refactor

#117 Feature/dockerize backend
  WebApp/backend/QuizMaster.API.Account/.dockerignore
  WebApp/backend/QuizMaster.API.Account/Dockerfile
  WebApp/backend/QuizMaster.API.Account/Program.cs
  WebApp/backend/QuizMaster.API.Account/Service/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Account/account.appsettings.Development.json
  WebApp/backend/QuizMaster.API.Account/account.appsettings.json
  WebApp/backend/QuizMaster.API.Account/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Authentication/.dockerignore
  WebApp/backend/QuizMaster.API.Authentication/Dockerfile
  WebApp/backend/QuizMaster.API.Authentication/Program.cs
  WebApp/backend/QuizMaster.API.Authentication/auth.appsettings.Development.json
  WebApp/backend/QuizMaster.API.Authentication/auth.appsettings.json
  WebApp/backend/QuizMaster.API.Authentication/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Gatewway/.dockerignore
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AuthenticationGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/MediaGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionDifficultyGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionTypeGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizCategoryGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Dockerfile
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/gateway.appsettings.Development.json
  WebApp/backend/QuizMaster.API.Gatewway/gateway.appsettings.json
  WebApp/backend/QuizMaster.API.Gatewway/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Media/.dockerignore
  WebApp/backend/QuizMaster.API.Media/Dockerfile
  WebApp/backend/QuizMaster.API.Media/Program.cs
  WebApp/backend/QuizMaster.API.Media/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Media/media.appsettings.Development.json
  WebApp/backend/QuizMaster.API.Media/media.appsettings.json
  WebApp/backend/QuizMaster.API.Monitoring/.dockerignore
  WebApp/backend/QuizMaster.API.Monitoring/Dockerfile
  WebApp/backend/QuizMaster.API.Monitoring/Program.cs
  WebApp/backend/QuizMaster.API.Monitoring/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Monitoring/monitoring.appsettings.Development.json
  WebApp/backend/QuizMaster.API.Monitoring/monitoring.appsettings.json
  WebApp/backend/QuizMaster.API.Quiz/.dockerignore
  WebApp/backend/QuizMaster.API.Quiz/Dockerfile
  WebApp/backend/QuizMaster.API.Quiz/Program.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Workers/QuizDataSynchronizationWorker.cs
  WebApp/backend/QuizMaster.API.Quiz/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Quiz/quiz.appsettings.Development.json
  WebApp/backend/QuizMaster.API.Quiz/quiz.appsettings.json
  WebApp/backend/QuizMaster.API.QuizSession/.dockerignore
  WebApp/backend/QuizMaster.API.QuizSession/Dockerfile
  WebApp/backend/QuizMaster.API.QuizSession/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Workers/QuestionSynchronizationWorkerService.cs
  WebApp/backend/QuizMaster.API.QuizSession/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.QuizSession/quizsession.appsettings.Development.json
  WebApp/backend/QuizMaster.API.QuizSession/quizsession.appsettings.json
  WebApp/docker-compose.yml
Labels: feature

#118 Session Patches
  WebApp/backend/QuizMaster.API.Account/Service/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Authentication/Models/AuthenticationRequestDTO.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AuthenticationGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
Labels: feature, fix

#114 [REF] Removed zombie codes.
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Quiz.Tests/QuestionCategoryControllerTests.cs
  WebApp/backend/QuizMaster.API.Quiz.Tests/QuestionControllerTests.cs
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionCategoryController.cs
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionController.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/OptionCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/OptionDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/QuestionCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/QuestionProfile.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/IAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/MultipleChoiceAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/PuzzleAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/SliderAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Answers/TypeAnswer.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/EmptyQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/MultipleChoicePlusAudioQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/MultipleChoiceQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/SliderQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Details/TypeAnswerQuestionDetail.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Questionnaire/Options/Option.cs
Labels: refactor

#121 [FIX] Fix configuration for monitoring service.
  WebApp/backend/QuizMaster.API.Monitoring/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/docker-compose.yml
Labels: fix
