Repository FS-FAST-TRACK/QuizMaster, pull requests merged in 2023-10, with the labels that each got.

#4 feat: Add QuizMasterAccount Module, Update userAccount and userRole in common library
  WebApp/backend/QuizMaster.API.Account/Controllers/AccountController.cs
  WebApp/backend/QuizMaster.API.Account/Controllers/WeatherForecastController.cs
  WebApp/backend/QuizMaster.API.Account/DbContext/AccountDbContext.cs
  WebApp/backend/QuizMaster.API.Account/Migrations/20231017161824_QuizMasterAccountInitialMigration.Designer.cs
  WebApp/backend/QuizMaster.API.Account/Migrations/20231017161824_QuizMasterAccountInitialMigration.cs
  WebApp/backend/QuizMaster.API.Account/Migrations/AccountDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Account/Program.cs
  WebApp/backend/QuizMaster.API.Account/QuizMaster.API.Account.csproj
  WebApp/backend/QuizMaster.API.Account/WeatherForecast.cs
  WebApp/backend/QuizMaster.API.Account/appsettings.Development.json
  WebApp/backend/QuizMaster.Library.Common/Entities/Accounts/UserAccount.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Details/UserRole.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Details/UserRoles.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Roles/UserRole.cs
  WebApp/backend/QuizMaster.Library.Common/Models/Account/AccountCreateDto.cs
  WebApp/backend/QuizMaster.Library.Common/Models/Account/AccountCreatePartialDto.cs
  WebApp/backend/QuizMaster.Library.Common/Models/Account/AccountDto.cs
  WebApp/backend/QuizMaster.Library.Common/Models/Response/ResponseDto.cs
  WebApp/backend/QuizMaster.Library.Common/QuizMaster.Library.Common.csproj
Labels: enhancement, feature

#3 feat: Cookie authentication is now functional, login/logout feature
  .github/workflows/backend.api.account.yml
  .github/workflows/backend.api.auth.yml
  .github/workflows/backend.api.media.yml
  .github/workflows/backend.api.monitoring.yml
  .github/workflows/backend.api.quiz.yml
  .github/workflows/backend.api.quizsession.yml
  README.md
  WebApp/backend/QuizMaster.API.Authentication/Configuration/AppSettings.cs
  WebApp/backend/QuizMaster.API.Authentication/Controllers/AuthenticationController.cs
  WebApp/backend/QuizMaster.API.Authentication/Controllers/WeatherForecastController.cs
  WebApp/backend/QuizMaster.API.Authentication/Helper/CookieFragment.cs
  WebApp/backend/QuizMaster.API.Authentication/Helper/CookieHelper.cs
  WebApp/backend/QuizMaster.API.Authentication/Models/AuthRequest.cs
  WebApp/backend/QuizMaster.API.Authentication/Models/AuthResponse.cs
  WebApp/backend/QuizMaster.API.Authentication/Program.cs
  WebApp/backend/QuizMaster.API.Authentication/QuizMaster.API.Authentication.csproj
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/AuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/IAuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Temp/IRepository.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Temp/Repository.cs
  WebApp/backend/QuizMaster.API.Authentication/WeatherForecast.cs
  WebApp/backend/QuizMaster.API.Authentication/appsettings.json
Labels: enhancement, feature

#9 feat: frontend project initialization
  WebApp/frontend/quiz-master/.eslintrc.json
  WebApp/frontend/quiz-master/.gitignore
  WebApp/frontend/quiz-master/README.md
  WebApp/frontend/quiz-master/app/favicon.ico
  WebApp/frontend/quiz-master/app/globals.css
  WebApp/frontend/quiz-master/app/layout.tsx
  WebApp/frontend/quiz-master/app/page.tsx
  WebApp/frontend/quiz-master/next.config.js
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz-master/postcss.config.js
  WebApp/frontend/quiz-master/public/next.svg
  WebApp/frontend/quiz-master/public/vercel.svg
  WebApp/frontend/quiz-master/tailwind.config.ts
  WebApp/frontend/quiz-master/tsconfig.json
  WebApp/frontend/remove_me_if_this_folder_is_filled
Labels: feature

#11 feat: Frontend project initialization
  WebApp/frontend/quiz-master/.eslintrc.json
  WebApp/frontend/quiz-master/.gitignore
  WebApp/frontend/quiz-master/README.md
  WebApp/frontend/quiz-master/app/favicon.ico
  WebApp/frontend/quiz-master/app/globals.css
  WebApp/frontend/quiz-master/app/layout.tsx
  WebApp/frontend/quiz-master/app/page.tsx
  WebApp/frontend/quiz-master/next.config.js
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz-master/postcss.config.js
  WebApp/frontend/quiz-master/public/next.svg
  WebApp/frontend/quiz-master/public/vercel.svg
  WebApp/frontend/quiz-master/tailwind.config.ts
  WebApp/frontend/quiz-master/tsconfig.json
  WebApp/frontend/remove_me_if_this_folder_is_filled
Labels: feature

#12 doc: update README
  README.md
Labels: documentation

#13 feat: Auth Service - Cookie Validation enhancement
  README.md
  WebApp/backend/QuizMaster.API.Authentication/Helper/CookieHelper.cs
  WebApp/backend/QuizMaster.API.Authentication/Models/AuthStore.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/AuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/IAuthenticationServices.cs
Labels: documentation, enhancement, feature

#14 Feat: Created API Gateway for Account Service
  WebApp/backend/QuizMaster.API.Account/Migrations/20231019091942_UpdateMigration.Designer.cs
  WebApp/backend/QuizMaster.API.Account/Migrations/20231019091942_UpdateMigration.cs
  WebApp/backend/QuizMaster.API.Account/Migrations/AccountDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Account/Profiles/UserAccountProfile.cs
  WebApp/backend/QuizMaster.API.Account/Program.cs
  WebApp/backend/QuizMaster.API.Account/Proto/accounts.proto
  WebApp/backend/QuizMaster.API.Account/QuizMaster.API.Account.csproj
  WebApp/backend/QuizMaster.API.Account/Service/InformationService.cs
  WebApp/backend/QuizMaster.API.Gatewway/AutoMapper.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/Properties/launchSettings.json
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gatewway.csproj
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.Development.json
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.json
  WebApp/backend/QuizMasterBackend.sln
Labels: feature

#20 feat: Media Microservice - Working Functionality
  WebApp/backend/QuizMaster.API.Media/Controllers/MediaController.cs
  WebApp/backend/QuizMaster.API.Media/Controllers/WeatherForecastController.cs
  WebApp/backend/QuizMaster.API.Media/Data/Context/FileDbContext.cs
  WebApp/backend/QuizMaster.API.Media/MediaDatabase.sqlite
  WebApp/backend/QuizMaster.API.Media/Migrations/20231023095706_SqliteMigration_1.Designer.cs
  WebApp/backend/QuizMaster.API.Media/Migrations/20231023095706_SqliteMigration_1.cs
  WebApp/backend/QuizMaster.API.Media/Migrations/FileDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Media/Models/FileInformation.cs
  WebApp/backend/QuizMaster.API.Media/Program.cs
  WebApp/backend/QuizMaster.API.Media/QuizMaster.API.Media.csproj
  WebApp/backend/QuizMaster.API.Media/Services/FileRepository.cs
  WebApp/backend/QuizMaster.API.Media/Services/IFileRepository.cs
  WebApp/backend/QuizMaster.API.Media/Utility/FileHandler.cs
  WebApp/backend/QuizMaster.API.Media/WeatherForecast.cs
  WebApp/backend/QuizMaster.API.Media/appsettings.json
  WebApp/backend/QuizMaster.API.Media/wwwroot/Images/00000000-0000-0000-0000-000000000000.png
Labels: feature

#21 feat: Media Microservice Working Functionality
  WebApp/backend/QuizMaster.API.Media/Controllers/MediaController.cs
  WebApp/backend/QuizMaster.API.Media/Controllers/WeatherForecastController.cs
  WebApp/backend/QuizMaster.API.Media/Data/Context/FileDbContext.cs
  WebApp/backend/QuizMaster.API.Media/MediaDatabase.sqlite
  WebApp/backend/QuizMaster.API.Media/Migrations/20231023095706_SqliteMigration_1.Designer.cs
  WebApp/backend/QuizMaster.API.Media/Migrations/20231023095706_SqliteMigration_1.cs
  WebApp/backend/QuizMaster.API.Media/Migrations/FileDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Media/Models/FileInformation.cs
  WebApp/backend/QuizMaster.API.Media/Program.cs
  WebApp/backend/QuizMaster.API.Media/QuizMaster.API.Media.csproj
  WebApp/backend/QuizMaster.API.Media/Services/FileRepository.cs
  WebApp/backend/QuizMaster.API.Media/Services/IFileRepository.cs
  WebApp/backend/QuizMaster.API.Media/Utility/FileHandler.cs
  WebApp/backend/QuizMaster.API.Media/WeatherForecast.cs
  WebApp/backend/QuizMaster.API.Media/appsettings.json
  WebApp/backend/QuizMaster.API.Media/wwwroot/Images/00000000-0000-0000-0000-000000000000.png
Labels: feature

#22 feat: Add CRUD functionality for question category, type, and difficulty.
  WebApp/backend/QuizMaster.API.Account/Controllers/AccountController.cs
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionCategoryController.cs
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionDifficultyController.cs
  WebApp/backend/QuizMaster.API.Quiz/Controllers/QuestionTypeController.cs
  WebApp/backend/QuizMaster.API.Quiz/DbContexts/QuestionDbContext.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/20231020121154_QuizMasterQuizInitialMigration.Designer.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/20231020121154_QuizMasterQuizInitialMigration.cs
  WebApp/backend/QuizMaster.API.Quiz/Migrations/QuestionDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/CategoryCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/CategoryDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/DifficultyCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/DifficultyDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/TypeCreateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/TypeDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Models/TypeUpdateDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/CategoryProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/DifficultyProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Profiles/TypeProfile.cs
  WebApp/backend/QuizMaster.API.Quiz/Program.cs
  WebApp/backend/QuizMaster.API.Quiz/QuizMaster.API.Quiz.csproj
  WebApp/backend/QuizMaster.API.Quiz/ResoureParameters/CategoryResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/ResoureParameters/IResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/SeedData/QuestionCategories.cs
  WebApp/backend/QuizMaster.API.Quiz/SeedData/QuestionDifficulties.cs
  WebApp/backend/QuizMaster.API.Quiz/SeedData/QuestionTypes.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/IQuizRepository.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/QuizRepository.cs
  WebApp/backend/QuizMaster.API.Quiz/appsettings.Development.json
Labels: feature

#29 fix: Unauthorized routes will now return 401 instead of 404(NotFound)
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AuthenticationGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/QuizMasterAuthorizationAttribute.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/QuizMasterAuthorizationFilter.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
Labels: fix

#33 feat: Added frontend testing dependencies
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
Labels: feature

#31 feat: RabbitMQ Service Enhancement
  WebApp/backend/QuizMaster.API.Authentication/Services/Worker/RabbitMqUserWorker.cs
Labels: enhancement

#34 Feat: added config files for testing
  WebApp/frontend/quiz-master/.eslintrc.json
  WebApp/frontend/quiz-master/__tests__/Home.test.tsx
  WebApp/frontend/quiz-master/jest.config.js
  WebApp/frontend/quiz-master/jest.setup.js
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
Labels: feature, fix

#37 Feat: added dependencies and initialized login form
  WebApp/frontend/quiz-master/__tests__/Home.test.tsx
  WebApp/frontend/quiz-master/api/auth/[...nextauth]/route.ts
  WebApp/frontend/quiz-master/app/globals.css
  WebApp/frontend/quiz-master/app/layout.tsx
  WebApp/frontend/quiz-master/app/page.tsx
  WebApp/frontend/quiz-master/components/login-form.tsx
  WebApp/frontend/quiz-master/jest.setup.js
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz-master/postcss.config.js
  WebApp/frontend/quiz-master/test-utils/render.tsx
  WebApp/frontend/quiz-master/types/next-auth.d.ts
Labels: feature, fix

#42 feat: Add categoryControllerTest for get categories.
  WebApp/backend/QuizMaster.API.Quiz.Tests/QuestionCategoryControllerTests.cs
  WebApp/backend/QuizMaster.API.Quiz.Tests/QuizMaster.API.Quiz.Tests.csproj
  WebApp/backend/QuizMaster.API.Quiz.Tests/Services/QuizTestDataRepository.cs
  WebApp/backend/QuizMaster.API.Quiz.Tests/UnitTest1.cs
Labels: feature

#43 fix: postcss config and mantine ui integration
  WebApp/frontend/quiz-master/app/layout.tsx
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz-master/postcss.config.js
  WebApp/frontend/quiz-master/tailwind.config.ts
Labels: fix

#47 Feat: media gateway
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/MediaGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/Properties/launchSettings.json
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.Gatewway/wwwroot/Images/82b688ab-9fab-43bf-aa66-ba2ccb50c56e.jpg
  WebApp/backend/QuizMaster.API.Gatewway/wwwroot/Images/83b8856d-4829-4169-bd7a-4693ae51ccfb.jpg
  WebApp/backend/QuizMaster.API.Gatewway/wwwroot/Images/ee814966-23b7-4ef6-bc8c-048c1eb0afe5.jpg
  WebApp/backend/QuizMaster.API.Media/MediaDatabase.sqlite
  WebApp/backend/QuizMaster.API.Media/Migrations/20231025110457_InitialMigrationOnGateway.Designer.cs
  WebApp/backend/QuizMaster.API.Media/Migrations/20231025110457_InitialMigrationOnGateway.cs
  WebApp/backend/QuizMaster.API.Media/Program.cs
  WebApp/backend/QuizMaster.API.Media/Proto/media.proto
  WebApp/backend/QuizMaster.API.Media/QuizMaster.API.Media.csproj
  WebApp/backend/QuizMaster.API.Media/Services/GRPC/Service.cs
Labels: feature

#52 FIx: Delete info if file not found
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/MediaGatewayController.cs
Labels: fix

#44 action-required: Success on dockerize services, failed gRPC connections
  WebApp/backend/%USERPROFILE%/.aspnet/https/aspnetapp.pfx
  WebApp/backend/QuizMaster.API.Account/Program.cs
  WebApp/backend/QuizMaster.API.Account/QuizMaster.API.Account.csproj
  WebApp/backend/QuizMaster.API.Account/Service/Worker/RabbitMqUserWorker.cs
  WebApp/backend/QuizMaster.API.Account/appsettings.Development.json
  WebApp/backend/QuizMaster.API.Account/appsettings.json
  WebApp/backend/QuizMaster.API.Account/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Authentication/Configuration/AppSettings.cs
  WebApp/backend/QuizMaster.API.Authentication/Program.cs
  WebApp/backend/QuizMaster.API.Authentication/QuizMaster.API.Authentication.csproj
  WebApp/backend/QuizMaster.API.Authentication/appsettings.Development.json
  WebApp/backend/QuizMaster.API.Authentication/appsettings.json
  WebApp/backend/QuizMaster.API.Authentication/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AuthenticationGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.Development.json
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.json
  WebApp/backend/QuizMaster.API.Gatewway/localhost_cert.pfx
  WebApp/backend/QuizMaster.API.Media/Program.cs
  docker-compose.yml
Labels: bug, help wanted
