Repository FS-FAST-TRACK/QuizMaster, pull requests merged in 2024-02, with the labels that each got.

#154 Fix: Single use of quiz room
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-shm
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/Protos/room.proto
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-wal
  WebApp/frontend/quiz_session/app/auth/util/handlers.js
Labels: feature, fix

#155 fix: fixed env and slider component from quiz_session
  WebApp/docker-compose.yml
  WebApp/frontend/quiz-master/.env
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/app/providers.tsx
  WebApp/frontend/quiz-master/app/quiz-rooms/create-quiz-room/page.tsx
  WebApp/frontend/quiz-master/lib/definitions.tsx
  WebApp/frontend/quiz-master/lib/hooks/quizRoom.tsx
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz_session/.env
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/util/api.js
  WebApp/frontend/quiz_session/app/util/store.js
Labels: enhancement, feature

#158 Head nav home
  .gitignore
  WebApp/backend/QuizMaster.API.Gatewway/Helper/Email/EmailTemplate.cs
  WebApp/backend/QuizMaster.API.Gatewway/Migrations/20240115085238_Migration_1_SystemInformation.cs
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/app/contact-us/page.tsx
  WebApp/frontend/quiz-master/app/page.tsx
  WebApp/frontend/quiz-master/app/system-info/layout.tsx
  WebApp/frontend/quiz-master/app/system-info/page.tsx
  WebApp/frontend/quiz-master/components/Commons/cards/ReviewPostedCard.tsx
  WebApp/frontend/quiz-master/components/Commons/cards/ReviewsCard.tsx
  WebApp/frontend/quiz-master/components/Commons/cards/SystemInfoCard.tsx
  WebApp/frontend/quiz-master/components/Commons/form/ContactUsForm.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/EditSystemInfoModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/FeedbackModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/UpdateContactInfoModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/contactDetails.tsx
  WebApp/frontend/quiz-master/components/Commons/navbars/head-nav.tsx
  WebApp/frontend/quiz-master/components/logout-button.tsx
  WebApp/frontend/quiz-master/lib/definitions.tsx
  WebApp/frontend/quiz-master/lib/hooks/contact-us.tsx
  WebApp/frontend/quiz-master/lib/hooks/system-info.tsx
  WebApp/frontend/quiz-master/lib/quizData.tsx
  WebApp/frontend/quiz-master/public/review-logo.svg
  WebApp/frontend/quiz-master/public/star-half-fill.svg
Labels: enhancement, feature, fix

#161 Swtmply fix/quiz session
  .gitignore
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/SystemController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/app/quiz-rooms/create-quiz-room/page.tsx
  WebApp/frontend/quiz-master/components/Commons/Pagination.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuizRoomTable.tsx
  WebApp/frontend/quiz-master/lib/queries/room.ts
  WebApp/frontend/quiz-master/store/QuizRoomStore.tsx
  WebApp/frontend/quiz_session/.env
  WebApp/frontend/quiz_session/app/room/quiz/components/dragAndDrop.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/multipleChoiceAudio.js
  WebApp/frontend/quiz_session/app/room/quiz/components/multipleChoiceImage.js
  WebApp/frontend/quiz_session/app/room/quiz/components/question.js
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
  WebApp/frontend/quiz_session/app/util/api.js
  WebApp/frontend/quiz_session/app/util/store.js
  WebApp/frontend/quiz_session/package-lock.json
  WebApp/frontend/quiz_session/package.json
Labels: feature, fix

#162 Feature Submit Screenshot Added
  .gitignore
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Utilities/QuizRoomExtension.cs
  WebApp/frontend/quiz-master/app/quiz-rooms/create-quiz-room/page.tsx
  WebApp/frontend/quiz_session/app/components/welcome.js
  WebApp/frontend/quiz_session/app/room/components/roomPin.js
  WebApp/frontend/quiz_session/app/room/quiz/components/dragAndDrop.js
  WebApp/frontend/quiz_session/app/room/quiz/components/modal.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/multipleChoiceAudio.js
  WebApp/frontend/quiz_session/app/room/quiz/components/multipleChoiceImage.js
  WebApp/frontend/quiz_session/app/room/quiz/components/questionImage.js
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
  WebApp/frontend/quiz_session/app/util/api.js
  WebApp/frontend/quiz_session/package-lock.json
  WebApp/frontend/quiz_session/package.json
Labels: feature

#163 Change the UI in the Admin Side
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/backend/QuizMaster.API.Media/MediaDatabase.sqlite
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db
  WebApp/frontend/quiz_session/app/room/components/chats.js
  WebApp/frontend/quiz_session/app/room/components/participants.js
  WebApp/frontend/quiz_session/app/room/components/room.js
  WebApp/frontend/quiz_session/app/room/components/roomPin.js
  WebApp/frontend/quiz_session/app/room/components/start.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/multipleChoiceAudio.js
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
  WebApp/frontend/quiz_session/app/util/api.js
  WebApp/frontend/quiz_session/app/util/useUserTokenData.js
  WebApp/frontend/quiz_session/package-lock.json
  WebApp/frontend/quiz_session/package.json
Labels: feature
