Repository FS-FAST-TRACK/QuizMaster, pull requests merged in 2024-03, with the labels that each got.

#169 MAJOR FIX FOR PRODUCTION
  WebApp/.env
  WebApp/backend/QuizMaster.API.Monitoring/Program.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Workers/QuestionSynchronizationWorkerService.cs
  WebApp/docker-compose.yml
  WebApp/frontend/quiz-master/.env
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/app/dashboard/layout.tsx
  WebApp/frontend/quiz-master/app/difficulties/layout.tsx
  WebApp/frontend/quiz-master/app/question-sets/layout.tsx
  WebApp/frontend/quiz-master/app/questions/layout.tsx
  WebApp/frontend/quiz-master/app/quiz-rooms/layout.tsx
  WebApp/frontend/quiz-master/lib/quizData.tsx
  WebApp/frontend/quiz-master/next.config.js
  WebApp/frontend/quiz_session/.env
  WebApp/frontend/quiz_session/app/room/quiz/components/multipleChoiceAudio.js
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
  WebApp/frontend/quiz_session/app/util/api.js
Labels: feature, fix

#173 Feature/system reports
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/backend/QuizMaster.API.Media/MediaDatabase.sqlite
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/app/globals.css
  WebApp/frontend/quiz-master/app/question-sets/create-set/page.tsx
  WebApp/frontend/quiz-master/app/question-sets/edit/[id]/page.tsx
  WebApp/frontend/quiz-master/app/reports/components/leaderboard.tsx
  WebApp/frontend/quiz-master/app/reports/components/loadingTable.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/IndividualParticipantAnswersReport.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/LeaderBoardTablePDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/ParticipantAnswersTablePDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/QuizSessionReportPDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/UsersReportPDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/UsersTablePDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/questionsReport.tsx
  WebApp/frontend/quiz-master/app/reports/components/sessionTable.tsx
  WebApp/frontend/quiz-master/app/reports/components/sessionsReport.tsx
  WebApp/frontend/quiz-master/app/reports/components/timeDateDuration.tsx
  WebApp/frontend/quiz-master/app/reports/components/usersReport.tsx
  WebApp/frontend/quiz-master/app/reports/components/usersTable.tsx
  WebApp/frontend/quiz-master/app/reports/layout.tsx
  WebApp/frontend/quiz-master/app/reports/page.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ExportModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewParticipantAnswersModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewQuestionModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewQuestionScreenShotModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewQuizSessionModal.tsx
  WebApp/frontend/quiz-master/lib/csvDataGenerator.tsx
  WebApp/frontend/quiz-master/lib/dateTimeUtils.tsx
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz-master/public/import-logo.svg
  WebApp/frontend/quiz-master/public/pie-sample.svg
Labels: feature, fix

#174 Removed pagination in Quiz Room, Fix pagination bug
  WebApp/frontend/quiz-master/app/quiz-rooms/page.tsx
  WebApp/frontend/quiz-master/components/Commons/Pagination.tsx
Labels: feature, fix

#175 Production/v 1
  WebApp/.env
  WebApp/backend/QuizMaster.API.Gatewway/Configuration/QuizSettings.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.json
  WebApp/backend/QuizMaster.API.Quiz/ResourceParameters/CategoryResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/ResourceParameters/DifficultyResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/ResourceParameters/IResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/ResourceParameters/QuestionResourceParameter.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Workers/QuizDataSynchronizationWorker.cs
  WebApp/backend/QuizMaster.API.QuizSession/Migrations/20240305095108_InitialMigration.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Workers/QuestionSynchronizationWorkerService.cs
  WebApp/backend/QuizMaster.Library.Common/Entities/Rooms/QuizParticipant.cs
  WebApp/docker-compose.yml
  WebApp/frontend/quiz-master/app/questions/create-question/page.tsx
  WebApp/frontend/quiz_session/app/room/quiz/components/leaderboard.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
Labels: feature, fix

#177 Production/v 1
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/frontend/quiz_session/app/room/quiz/components/leaderboard.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
Labels: fix

#179 Production/v 1
  WebApp/docker-compose-no-frontend.yml
  WebApp/frontend/quiz_session/app/auth/componts/Login.js
  WebApp/frontend/quiz_session/app/room/components/participants.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
  start_production.bat
Labels: feature, fix

#181 Fixed Button CSS Visibility in sysinfo,contact-us,feedback
  WebApp/frontend/quiz-master/components/Commons/form/ContactUsForm.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/EditSystemInfoModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/FeedbackModal.tsx
  WebApp/frontend/quiz-master/lib/hooks/question.tsx
Labels: fix

#185 Possible Fix: ViewParticipantAnswersModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewParticipantAnswersModal.tsx
Labels: fix

#186 Feat: Add question statement on export PDF quiz session
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/LeaderBoardTablePDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/ParticipantAnswersTablePDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/QuizSessionReportPDF.tsx
  WebApp/frontend/quiz-master/app/reports/components/sessionTable.tsx
  WebApp/frontend/quiz-master/app/reports/components/usersReport.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewParticipantAnswersModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewQuizSessionModal.tsx
Labels: feature

#189 Production/v 1
  WebApp/.env
  WebApp/backend/QuizMaster.API.Monitoring/Program.cs
  WebApp/frontend/quiz-master/.env
  WebApp/frontend/quiz-master/app/api/auth/[...nextauth]/route.ts
  WebApp/frontend/quiz-master/app/auth/[authPage]/page.tsx
  WebApp/frontend/quiz-master/app/page.tsx
  WebApp/frontend/quiz-master/app/question-sets/edit/[id]/page.tsx
  WebApp/frontend/quiz-master/app/questions/create-question/page.tsx
  WebApp/frontend/quiz-master/app/questions/layout.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/ParticipantAnswersTablePDF.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetails/MultipleChoice.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewQuizSessionModal.tsx
  WebApp/frontend/quiz-master/components/Commons/navbars/head-nav.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuestionTable.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuizRoomTable.tsx
  WebApp/frontend/quiz-master/lib/quizData.tsx
  WebApp/frontend/quiz-master/store/QuestionStore.tsx
  WebApp/frontend/quiz_session/app/room/components/room.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
  WebApp/frontend/quiz_session/app/util/api.js
Labels: feature, fix

#195 Production/v 1
  WebApp/.env
  WebApp/backend/QuizMaster.API.Gatewway/Configuration/QuizSettings.cs
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.json
  WebApp/docker-compose.yml
  WebApp/frontend/quiz-master/.env
  WebApp/frontend/quiz_session/.env
  WebApp/frontend/quiz_session/app/room/quiz/components/header.js
Labels: feature, fix

#196 Fix: Possible fix for truncated Individual Report PDF
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/IndividualParticipantAnswersReport.tsx
  WebApp/frontend/quiz-master/app/reports/components/pdfReports/LeaderBoardTablePDF.tsx
Labels: fix

#197 Fix: Fix padding and alignment elements on quiz session header
  WebApp/frontend/quiz_session/app/room/quiz/components/header.js
Labels: fix

#198 Production/v 1
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/frontend/quiz_session/app/room/quiz/components/interval.js
Labels: feature

#200 Production/v 1
  MobileApp/README.md
  MobileApp/backend/remove_me_if_this_folder_is_filled
  MobileApp/frontend/remove_me_if_this_folder_is_filled
  WebApp/.env
  WebApp/backend/QuizMaster.API.Gatewway/Configuration/QuizSettings.cs
  WebApp/backend/QuizMaster.API.Gatewway/Models/Report/ParticipantAnswerReport.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.json
  WebApp/backend/QuizMaster.API.Quiz/Models/QuestionDto.cs
  WebApp/backend/QuizMaster.API.Quiz/Services/Repositories/QuizRepository.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizRoomServices.cs
  WebApp/backend/QuizMaster.API.QuizSession/Services/Grpc/QuizSetServices.cs
  WebApp/docker-compose-no-frontend.yml
  WebApp/docker-compose.yml
  WebApp/frontend/quiz-master/app/dashboard/game.tsx
  WebApp/frontend/quiz-master/lib/correctAnswerUtils.tsx
  WebApp/frontend/quiz_session/.env
  WebApp/frontend/quiz_session/app/components/welcome.js
  WebApp/frontend/quiz_session/app/room/components/chat.js
  WebApp/frontend/quiz_session/app/room/components/chats.js
  WebApp/frontend/quiz_session/app/room/components/roomPin.js
  WebApp/frontend/quiz_session/app/room/components/start.js
  WebApp/frontend/quiz_session/app/room/quiz/components/AnimateSlideInFromBottom.js
  WebApp/frontend/quiz_session/app/room/quiz/components/ParticipantName.js
  WebApp/frontend/quiz_session/app/room/quiz/components/header.js
  WebApp/frontend/quiz_session/app/room/quiz/components/interval.js
  WebApp/frontend/quiz_session/app/room/quiz/components/progress.js
  WebApp/frontend/quiz_session/app/room/quiz/modals/ConfirmEndGameModal.jsx
  WebApp/frontend/quiz_session/app/util/api.js
  WebApp/frontend/quiz_session/next.config.js
  WebApp/frontend/quiz_session/package-lock.json
  WebApp/frontend/quiz_session/package.json
Labels: enhancement, feature, fix
