Repository FS-FAST-TRACK/QuizMaster, pull requests merged in 2024-01, with the labels that each got.

#123 Feat: Introduced Get and Create room routes in Gateway for admin use
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
Labels: feature

#126 Refactor: Authorization Filters results are updated
  WebApp/backend/QuizMaster.API.Gatewway/Attributes/QuizMasterAdminAuthorizationAttribute.cs
  WebApp/backend/QuizMaster.API.Gatewway/Attributes/QuizMasterAuthorizationAttribute.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AuthenticationGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/MediaGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizCategoryGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Filters/QuizMasterAdminAuthorizationFilter.cs
  WebApp/backend/QuizMaster.API.Gatewway/Filters/QuizMasterAuthorizationFilter.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/QuizMasterControllerExtension.cs
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
Labels: refactor

#127 Feature/quizmaster frontend web maintenance
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuizSetGatewayController.cs
  WebApp/frontend/quiz-master/app/question-sets/create-set/page.tsx
  WebApp/frontend/quiz-master/app/question-sets/edit/[id]/page.tsx
  WebApp/frontend/quiz-master/components/Commons/cards/SetCard.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/AddQuestionToSetModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewQuestionModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewSetModal.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuestionTable.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/SetsTable.tsx
  WebApp/frontend/quiz-master/components/login-form.tsx
  WebApp/frontend/quiz-master/lib/definitions.tsx
  WebApp/frontend/quiz-master/lib/hooks/set.tsx
  WebApp/frontend/quiz-master/lib/quizData.tsx
Labels: feature

#125 Ref/quizmaster backend maintenance module
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/QuestionDetailGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Dockerfile
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.Quiz/Program.cs
  WebApp/backend/QuizMaster.API.Quiz/Protos/quiz_questionDetail.proto
  WebApp/backend/QuizMaster.API.Quiz/QuizMaster.API.Quiz.csproj
  WebApp/backend/QuizMaster.API.Quiz/Services/GRPC/QuestionDetailsService.cs
  WebApp/docker-compose.yml
Labels: refactor

#129 Feat: Added Metadata for QuizSession In-Game
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
Labels: feature

#130 [REFACTOR]: Quizmaster Authorization pages.
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/api/definitions.ts
  WebApp/frontend/quiz-master/app/auth/[authPage]/page.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuestionTable.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/SetsTable.tsx
  WebApp/frontend/quiz-master/components/login-form.tsx
  WebApp/frontend/quiz-master/components/pages/ErrorConnectionRefused.tsx
  WebApp/frontend/quiz-master/components/pages/ErrorContainer.tsx
  WebApp/frontend/quiz-master/components/pages/ErrorInternal.tsx
  WebApp/frontend/quiz-master/components/register-form.tsx
  WebApp/frontend/quiz-master/lib/hooks/auth.ts
  WebApp/frontend/quiz-master/lib/hooks/category.tsx
  WebApp/frontend/quiz-master/lib/hooks/questionDetails.tsx
  WebApp/frontend/quiz-master/lib/hooks/set.tsx
  WebApp/frontend/quiz-master/lib/quizData.tsx
  WebApp/frontend/quiz-master/lib/validation/creators.ts
  WebApp/frontend/quiz-master/lib/validation/regex.ts
  WebApp/frontend/quiz-master/lib/validation/validate.ts
  WebApp/frontend/quiz-master/utils/errorRedirection.ts
Labels: refactor

#133 Feat: Added alert, notification, countdown on leaderboard
  WebApp/backend/QuizMaster.API.Gatewway/Hubs/SessionHub.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/Migrations/20240103111611_InitialMigration.Designer.cs
  WebApp/backend/QuizMaster.API.QuizSession/Migrations/20240103111611_InitialMigration.cs
  WebApp/backend/QuizMaster.API.QuizSession/Migrations/QuizSessionDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/frontend/quiz_session/app/auth/code/components/Code.js
  WebApp/frontend/quiz_session/app/auth/util/handlers.js
  WebApp/frontend/quiz_session/app/components/welcome.js
  WebApp/frontend/quiz_session/app/layout.js
  WebApp/frontend/quiz_session/app/room/components/chats.js
  WebApp/frontend/quiz_session/app/room/components/message.js
  WebApp/frontend/quiz_session/app/room/components/participants.js
  WebApp/frontend/quiz_session/app/room/components/start.js
  WebApp/frontend/quiz_session/app/room/quiz/components/header.js
  WebApp/frontend/quiz_session/app/room/quiz/components/interval.js
  WebApp/frontend/quiz_session/app/room/quiz/components/progress.js
  WebApp/frontend/quiz_session/app/room/quiz/components/question.js
  WebApp/frontend/quiz_session/app/util/api.js
  WebApp/frontend/quiz_session/app/util/store.js
  WebApp/frontend/quiz_session/package-lock.json
  WebApp/frontend/quiz_session/package.json
Labels: feature

#134 [Feature, Refactor] quizmaster frontend web maintenance
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/frontend/quiz-master/api/definitions.ts
  WebApp/frontend/quiz-master/app/auth/signout/page.tsx
  WebApp/frontend/quiz-master/app/difficulties/page.tsx
  WebApp/frontend/quiz-master/app/question-sets/layout.tsx
  WebApp/frontend/quiz-master/app/questions/create-question/page.tsx
  WebApp/frontend/quiz-master/app/questions/layout.tsx
  WebApp/frontend/quiz-master/app/questions/page.tsx
  WebApp/frontend/quiz-master/components/Commons/cards/SetCard.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/AddQuestionToSetModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/ViewSetModal.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuestionTable.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/SetsTable.tsx
  WebApp/frontend/quiz-master/lib/helpers.tsx
  WebApp/frontend/quiz-master/lib/hooks/category.tsx
  WebApp/frontend/quiz-master/lib/hooks/difficulty.tsx
  WebApp/frontend/quiz-master/lib/hooks/question.tsx
  WebApp/frontend/quiz-master/lib/hooks/type.tsx
  WebApp/frontend/quiz-master/lib/quizData.tsx
Labels: feature, refactor

#138 Fix: Leaderboard Update
  WebApp/frontend/quiz_session/app/components/welcome.js
  WebApp/frontend/quiz_session/app/room/quiz/components/progress.js
  WebApp/frontend/quiz_session/app/room/quiz/components/question.js
Labels: fix

#141 Fix: fix the participant and number and leaderboard
  WebApp/backend/QuizMaster.API.Gatewway/Services/QuizHandler.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizSession.db
  WebApp/frontend/quiz_session/app/room/components/chat.js
  WebApp/frontend/quiz_session/app/room/components/chatDetail.js
  WebApp/frontend/quiz_session/app/room/components/message.js
Labels: fix

#142 Feature/quizmaster frontend profile maintenance
  .gitignore
  WebApp/backend/QuizMaster.API.Account/Configuration/ApplicationSettings.cs
  WebApp/backend/QuizMaster.API.Account/Program.cs
  WebApp/backend/QuizMaster.API.Account/Proto/accounts.proto
  WebApp/backend/QuizMaster.API.Account/Service/EmailSenderService.cs
  WebApp/backend/QuizMaster.API.Account/Service/InformationService.cs
  WebApp/backend/QuizMaster.API.Account/Service/PasswordHandler.cs
  WebApp/backend/QuizMaster.API.Account/appsettings.json
  WebApp/backend/QuizMaster.API.Authentication/Services/Auth/AuthenticationServices.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.QuizSession/QuizMaster.API.QuizSession.csproj
  WebApp/backend/QuizMaster.API.QuizSession/appsettings.Development.json
  WebApp/backend/QuizMaster.Library.Common/Models/Accounts/ChangePasswordDTO.cs
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/app/profile/layout.tsx
  WebApp/frontend/quiz-master/app/profile/page.tsx
  WebApp/frontend/quiz-master/components/Commons/navbars/UserNavBar.tsx
  WebApp/frontend/quiz-master/components/Commons/profile/EditField.tsx
  WebApp/frontend/quiz-master/components/Commons/profile/EditFieldWithButton.tsx
  WebApp/frontend/quiz-master/components/Commons/profile/SaveCancelButton.tsx
  WebApp/frontend/quiz-master/lib/hooks/profile.ts
  WebApp/frontend/quiz-master/store/ProfileStore.tsx
Labels: feature

#143 [feat] Added the quiz room pages.
  WebApp/frontend/quiz-master/api/api-routes.ts
  WebApp/frontend/quiz-master/app/auth/[authPage]/page.tsx
  WebApp/frontend/quiz-master/app/quiz-rooms/create-quiz-room/page.tsx
  WebApp/frontend/quiz-master/app/quiz-rooms/layout.tsx
  WebApp/frontend/quiz-master/app/quiz-rooms/loading.tsx
  WebApp/frontend/quiz-master/app/quiz-rooms/page.tsx
  WebApp/frontend/quiz-master/components/Commons/Pagination.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuizRoomTable.tsx
  WebApp/frontend/quiz-master/lib/definitions/quizRoom.ts
  WebApp/frontend/quiz-master/lib/validation/creators.ts
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz-master/store/ConnectionStore.tsx
  WebApp/frontend/quiz-master/store/QuizRoomStore.tsx
Labels: feature

#139 [Feature, Fix, Refactor]: Quizmaster frontend web maintenance
  .gitignore
  WebApp/frontend/quiz-master/app/contact-us/layout.tsx
  WebApp/frontend/quiz-master/app/contact-us/page.tsx
  WebApp/frontend/quiz-master/app/page.tsx
  WebApp/frontend/quiz-master/app/question-sets/page.tsx
  WebApp/frontend/quiz-master/app/questions/create-question/page.tsx
  WebApp/frontend/quiz-master/app/questions/edit/[id]/layout.tsx
  WebApp/frontend/quiz-master/app/questions/edit/[id]/page.tsx
  WebApp/frontend/quiz-master/app/questions/page.tsx
  WebApp/frontend/quiz-master/app/system-info/layout.tsx
  WebApp/frontend/quiz-master/app/system-info/page.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetails/MultipleChoice.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetails/Puzzle.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/MultipleChoice.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/MultipleChoicePlusAudio.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/Puzzle.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/Slider.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/TrueOrFalse.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/TypeAnwer.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/index.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsEdit/utils.ts
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsView/Puzzle.tsx
  WebApp/frontend/quiz-master/components/Commons/QuestionDetailsView/index.tsx
  WebApp/frontend/quiz-master/components/Commons/cards/SystemInfoCard.tsx
  WebApp/frontend/quiz-master/components/Commons/form/ContactUsForm.tsx
  WebApp/frontend/quiz-master/components/Commons/inputs/PuzzleInput.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/AddQuestionToSetModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/EditSystemInfoModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/FeedbackModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/UpdateContactInfoModal.tsx
  WebApp/frontend/quiz-master/components/Commons/modals/contactDetails.tsx
  WebApp/frontend/quiz-master/components/Commons/navbars/head-nav.tsx
  WebApp/frontend/quiz-master/components/Commons/tables/QuestionTable.tsx
  WebApp/frontend/quiz-master/lib/definitions.tsx
  WebApp/frontend/quiz-master/lib/hooks/category.tsx
  WebApp/frontend/quiz-master/lib/hooks/contact-us.tsx
  WebApp/frontend/quiz-master/lib/hooks/question.tsx
  WebApp/frontend/quiz-master/lib/hooks/questionDetails.tsx
  WebApp/frontend/quiz-master/lib/hooks/system-info.tsx
  WebApp/frontend/quiz-master/lib/quizData.tsx
  WebApp/frontend/quiz-master/middleware.ts
  WebApp/frontend/quiz-master/public/amico.svg
  WebApp/frontend/quiz-master/public/android-icon.png
  WebApp/frontend/quiz-master/public/apple-icon.png
  WebApp/frontend/quiz-master/public/contact-us-image.png
  WebApp/frontend/quiz-master/public/edit-icon.svg
  WebApp/frontend/quiz-master/public/email-icon.png
  WebApp/frontend/quiz-master/public/quiz-master-icon-white.png
  WebApp/frontend/quiz-master/public/quiz-master-icon-white.svg
  WebApp/frontend/quiz-master/public/quiz-master-logo-white.png
  WebApp/frontend/quiz-master/public/star-fill.svg
  WebApp/frontend/quiz-master/public/star.svg
  WebApp/frontend/quiz-master/public/telephone-icon.png
  WebApp/frontend/quiz-master/public/user-icon.svg
  WebApp/frontend/quiz-master/public/web-icon.png
Labels: feature

#144 Feature/System Modules
  WebApp/backend/QuizMaster.API.Authentication/Controllers/AuthenticationController.cs
  WebApp/backend/QuizMaster.API.Gatewway/AutoMapper.cs
  WebApp/backend/QuizMaster.API.Gatewway/Configuration/ApplicationSettings.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/SystemController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Helper/Email/EmailTemplate.cs
  WebApp/backend/QuizMaster.API.Gatewway/Migrations/20240115085238_Migration_1_SystemInformation.Designer.cs
  WebApp/backend/QuizMaster.API.Gatewway/Migrations/20240115085238_Migration_1_SystemInformation.cs
  WebApp/backend/QuizMaster.API.Gatewway/Migrations/20240115131703_Migration_2_RemovedUnusedProp.Designer.cs
  WebApp/backend/QuizMaster.API.Gatewway/Migrations/20240115131703_Migration_2_RemovedUnusedProp.cs
  WebApp/backend/QuizMaster.API.Gatewway/Migrations/SystemDbContextModelSnapshot.cs
  WebApp/backend/QuizMaster.API.Gatewway/Models/System/AboutModel.cs
  WebApp/backend/QuizMaster.API.Gatewway/Models/System/ContactModel.cs
  WebApp/backend/QuizMaster.API.Gatewway/Models/System/ReviewModel.cs
  WebApp/backend/QuizMaster.API.Gatewway/Models/System/SubmitContactModel.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/QuizMaster.API.Gateway.csproj
  WebApp/backend/QuizMaster.API.Gatewway/Services/Email/EmailService.cs
  WebApp/backend/QuizMaster.API.Gatewway/Services/SystemService/SystemRepository.cs
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/Contexts/SystemDbContext.cs
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-shm
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-wal
  WebApp/backend/QuizMaster.API.Gatewway/appsettings.json
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-wal
  WebApp/backend/QuizMaster.Library.Common/Utilities/JWTHelper.cs
Labels: feature, fix

#150 Password Reset Implementation
  WebApp/backend/QuizMaster.API.Account/Proto/accounts.proto
  WebApp/backend/QuizMaster.API.Account/Service/EmailSenderService.cs
  WebApp/backend/QuizMaster.API.Account/Service/InformationService.cs
  WebApp/backend/QuizMaster.API.Gatewway/Controllers/AccountGatewayController.cs
  WebApp/backend/QuizMaster.API.Gatewway/Program.cs
  WebApp/backend/QuizMaster.API.Gatewway/Views/PasswordChange/Index.cshtml
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-wal
Labels: feature

#151 Added functionality to the question type UI
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-shm
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-wal
  WebApp/backend/QuizMaster.API.Media/MediaDatabase.sqlite
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231115091318_initialDbAudit.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231115091318_initialDbAudit.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231120094711_AddQuizAuditTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231120094711_AddQuizAuditTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231123110624_addUserIdOnQuizAuditTrailTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231123110624_addUserIdOnQuizAuditTrailTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231123112259_addUserRoleQuizAuditTrailTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231123112259_addUserRoleQuizAuditTrailTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231128084632_addUserNameQuizAuditTrailTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231128084632_addUserNameQuizAuditTrailTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231129052315_removequizid.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231129052315_removequizid.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231129113916_AddQuizDiffAuditTrailTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231129113916_AddQuizDiffAuditTrailTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231204075112_AddQuestionAuditTrail.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231204075112_AddQuestionAuditTrail.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231204094139_AddQuestionIdQuestionAuditTrail.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231204094139_AddQuestionIdQuestionAuditTrail.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231205094208_removeQuestionIdprop.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231205094208_removeQuestionIdprop.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231206114456_QuestionTypeAuditTrailTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231211081844_MediaAuditTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231211081844_MediaAuditTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231218080354_AddQuizSetAuditTable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20231218080354_AddQuizSetAuditTable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20240105091931_addroomaudittrailtable.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20240105091931_addroomaudittrailtable.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20240110113353_addusername.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20240110113353_addusername.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20240118100133_InitialMigrationOnRestart.Designer.cs
  WebApp/backend/QuizMaster.API.Monitoring/Migrations/20240118100133_InitialMigrationOnRestart.cs
  WebApp/backend/QuizMaster.API.Monitoring/QuizMaster.API.Monitoring.csproj
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db
  WebApp/frontend/quiz_session/app/auth/componts/Login.js
  WebApp/frontend/quiz_session/app/components/welcome.js
  WebApp/frontend/quiz_session/app/room/quiz/components/dragAndDrop.js
  WebApp/frontend/quiz_session/app/room/quiz/components/header.js
  WebApp/frontend/quiz_session/app/room/quiz/components/leaderboard.js
  WebApp/frontend/quiz_session/app/room/quiz/components/modal.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/multipleChoiceAudio.js
  WebApp/frontend/quiz_session/app/room/quiz/components/question.js
  WebApp/frontend/quiz_session/app/room/quiz/components/questionImage.js
  WebApp/frontend/quiz_session/app/room/quiz/components/slider.js
  WebApp/frontend/quiz_session/app/room/quiz/components/trueOrFalse.js
  WebApp/frontend/quiz_session/app/room/quiz/components/typeAnswer.js
  WebApp/frontend/quiz_session/app/util/api.js
  WebApp/frontend/quiz_session/app/util/store.js
  WebApp/frontend/quiz_session/next.config.js
  WebApp/frontend/quiz_session/package-lock.json
  WebApp/frontend/quiz_session/package.json
  WebApp/frontend/quiz_session/public/icons/drag.png
  WebApp/frontend/quiz_session/public/icons/image.png
Labels: feature

#152 Ref: Refactor the quiz session UI
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-shm
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-wal
  WebApp/frontend/quiz-master/app/dashboard/game.tsx
  WebApp/frontend/quiz-master/app/dashboard/page.tsx
  WebApp/frontend/quiz_session/app/auth/code/components/Code.js
  WebApp/frontend/quiz_session/app/auth/componts/Login.js
  WebApp/frontend/quiz_session/app/auth/util/handlers.js
  WebApp/frontend/quiz_session/app/components/welcome.js
  WebApp/frontend/quiz_session/app/layout.js
  WebApp/frontend/quiz_session/app/page.jsx
  WebApp/frontend/quiz_session/app/room/quiz/components/leaderboard.js
  WebApp/frontend/quiz_session/app/room/quiz/components/mulitpleChoice.js
  WebApp/frontend/quiz_session/app/room/quiz/components/question.js
  WebApp/frontend/quiz_session/app/room/quiz/page.js
  WebApp/frontend/quiz_session/app/util/api.js
Labels: refactor, fix

#153 Feat: Added encryption on token
  WebApp/backend/QuizMaster.API.Gatewway/Services/SessionHandler.cs
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-shm
  WebApp/backend/QuizMaster.API.Gatewway/SystemData/System.db-wal
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-shm
  WebApp/backend/QuizMaster.API.QuizSession/sessionDb/QuizSession.db-wal
  WebApp/frontend/quiz-master/app/dashboard/game.tsx
  WebApp/frontend/quiz-master/package-lock.json
  WebApp/frontend/quiz-master/package.json
  WebApp/frontend/quiz-master/tsconfig.json
  WebApp/frontend/quiz_session/app/auth/componts/Login.js
  WebApp/frontend/quiz_session/app/auth/page.js
  WebApp/frontend/quiz_session/app/components/welcome.js
  WebApp/frontend/quiz_session/app/room/quiz/components/leaderboard.js
  WebApp/frontend/quiz_session/app/room/quiz/components/question.js
  WebApp/frontend/quiz_session/package-lock.json
  WebApp/frontend/quiz_session/package.json
  WebApp/frontend/quiz_session/tailwind.config.js
Labels: enhancement, feature, refactor
